server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /customer-api/ {
        proxy_pass http://customer-service:8081/;
    }

    location /restaurant-api/ {
        proxy_pass http://restaurant-service:8082/;
    }

    location /order-api/ {
        proxy_pass http://order-service:8083/;
    }

    location /delivery-api/ {
        proxy_pass http://delivery-service:8085/;
    }

    location /admin-api/ {
        proxy_pass http://admin-service:8087/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
